import _ from 'lodash'

const data: Array<string> = [
	'Scout Tuazon',
	'QC Circle',
	'Quezon Ave.',
	'Taytay',
	'Sumulong',
	'Pasig Kapitolyo',
	'Forbestown Center',
	'Antipolo',
	'Uptown Mall',
	'Jupiter',
	'Commonwealth',
	'Sucat',
	'Baclaran',
	'Las Piñas',
	'Dasma',
	'Bacoor',
	'Tagaytay',
	'Kawit',
	'Orosa',
	'EDSA Caloocan',
	'Ali Mall',
	'Commonwealth Fairview',
	'E.Rodriguez',
	'Farmers Plaza',
	'Greenbelt',
	'Greenhills',
	'Hampton',
	'Matalino',
	'Pasig Kapitolyo',
	'Regalado',
	'RPL Galleria',
	'RPL Magnolia',
	'Shangrila Plaza',
	'SM East Ortigas',
	'SM Fairview',
	'SM Marikina',
	'SM Masinag',
	'SM Megamall',
	'SM Novaliches',
	'SM San Jose Del Monte',
	'SM Sta Mesa',
	'SM Taytay',
	'Smart Araneta',
	'Tiendesitas',
	'Valero',
	'Waltermart Makati',
	'Balibago Angeles',
	'Banawe',
	'Luisita Tarlac',
	'Shell NLEX Mexico',
	'SM Baguio',
	'SM North Edsa',
	'SM Rosales',
	'SM Los Banos',
	'Molino Boulevard',
	'Nuvali',
	'Shell SLEX',
	'SM Bacoor',
	'SM Bicutan',
	'SM MOA',
	'SM Southmall',
	'Banilad'
]

export default _.sortBy(data)
